// Расширенные данные товаров
const products = [
    {
        id: 1,
        name: "iPhone 15 Pro Max",
        price: 129990,
        discountPrice: 119990,
        category: "smartphones",
        description: "Флагманский смартфон Apple с титановым корпусом и продвинутой камерной системой",
        specs: ["6.7'' Super Retina XDR", "1TB Память", "Титановый корпус", "48 Мп основная камера", "A17 Pro chip"],
        inStock: true,
        rating: 4.9,
        reviews: 324,
        isNew: true,
        fastDelivery: true,
        popular: true
    },
    {
        id: 2,
        name: "Samsung Galaxy S24 Ultra",
        price: 99990,
        category: "smartphones",
        description: "Мощный смартфон с AI-функциями и S-Pen для максимальной продуктивности",
        specs: ["6.8'' Dynamic AMOLED 2X", "512 ГБ", "S-Pen", "200 Мп камера", "Snapdragon 8 Gen 3"],
        inStock: true,
        rating: 4.8,
        reviews: 287,
        isNew: true,
        fastDelivery: true,
        popular: true
    },
    {
        id: 3,
        name: "MacBook Pro 16'' M3 Max",
        price: 299990,
        discountPrice: 279990,
        category: "laptops",
        description: "Профессиональный ноутбук для творчества и разработки с чипом Apple M3 Max",
        specs: ["16.2'' Liquid Retina XDR", "M3 Max 16-core", "48GB RAM", "1TB SSD", "120Hz ProMotion"],
        inStock: true,
        rating: 4.9,
        reviews: 156,
        isNew: true,
        fastDelivery: false,
        popular: false
    },
    {
        id: 4,
        name: "ASUS ROG Strix SCAR 18",
        price: 249990,
        category: "laptops",
        description: "Экстремальный игровой ноутбук с топовой видеокартой и процессором Intel",
        specs: ["18'' QHD+ 240Hz", "Intel Core i9-14900HX", "RTX 4090", "64GB DDR5", "2TB NVMe"],
        inStock: false,
        rating: 4.7,
        reviews: 89,
        isNew: false,
        fastDelivery: false,
        popular: true
    },
    {
        id: 5,
        name: "Sony WH-1000XM5",
        price: 34990,
        discountPrice: 29990,
        category: "audio",
        description: "Беспроводные наушники с продвинутым шумоподавлением и премиум звуком",
        specs: ["Активное шумоподавление", "30 часов работы", "Touch управление", "Hi-Res Audio", "Быстрая зарядка"],
        inStock: true,
        rating: 4.8,
        reviews: 412,
        isNew: false,
        fastDelivery: true,
        popular: true
    },
    {
        id: 6,
        name: "Apple AirPods Pro 2",
        price: 24990,
        category: "audio",
        description: "Продвинутые наушники с пространственным аудио и улучшенным шумоподавлением",
        specs: ["Пространственное аудио", "Активное шумоподавление", "6ч работы", "MagSafe чехол", "Управление жестами"],
        inStock: true,
        rating: 4.7,
        reviews: 534,
        isNew: false,
        fastDelivery: true,
        popular: true
    },
    {
        id: 7,
        name: "iPad Pro 12.9'' M2",
        price: 109990,
        discountPrice: 99990,
        category: "tablets",
        description: "Мощный планшет для профессионалов с дисплеем Liquid Retina XDR",
        specs: ["12.9'' Liquid Retina XDR", "Apple M2 chip", "2TB Память", "5G", "Apple Pencil 2"],
        inStock: true,
        rating: 4.8,
        reviews: 234,
        isNew: true,
        fastDelivery: true,
        popular: false
    },
    {
        id: 8,
        name: "Samsung Galaxy Tab S9 Ultra",
        price: 89990,
        category: "tablets",
        description: "Флагманский планшет с огромным экраном и S-Pen в комплекте",
        specs: ["14.6'' Dynamic AMOLED 2X", "Snapdragon 8 Gen 2", "12GB RAM", "512GB", "S-Pen включен"],
        inStock: true,
        rating: 4.6,
        reviews: 167,
        isNew: true,
        fastDelivery: true,
        popular: true
    },
    {
        id: 9,
        name: "Apple Watch Series 9",
        price: 41990,
        discountPrice: 37990,
        category: "wearables",
        description: "Умные часы с продвинутыми функциями здоровья и новым чипом S9",
        specs: ["45mm Retina display", "S9 SiP", "ECG", "SpO2", "Always-On display"],
        inStock: true,
        rating: 4.7,
        reviews: 189,
        isNew: true,
        fastDelivery: true,
        popular: true
    },
    {
        id: 10,
        name: "Samsung Galaxy Watch 6 Classic",
        price: 35990,
        category: "wearables",
        description: "Премиум умные часы с вращающимся безелем и полным мониторингом здоровья",
        specs: ["47mm Super AMOLED", "Exynos W930", "ECG", "BIA", "Rotating bezel"],
        inStock: true,
        rating: 4.6,
        reviews: 145,
        isNew: true,
        fastDelivery: true,
        popular: false
    },
    {
        id: 11,
        name: "PlayStation 5 Pro",
        price: 59990,
        category: "gaming",
        description: "Новейшая игровая консоль с поддержкой 8K и трассировкой лучей",
        specs: ["8K Gaming", "Ray Tracing", "1TB SSD", "120fps", "Backward compatibility"],
        inStock: false,
        rating: 4.9,
        reviews: 0,
        isNew: true,
        fastDelivery: false,
        popular: true
    },
    {
        id: 12,
        name: "Xbox Series X",
        price: 49990,
        discountPrice: 44990,
        category: "gaming",
        description: "Мощная игровая консоль с Game Pass и поддержкой 4K 120fps",
        specs: ["4K 120fps", "1TB SSD", "Game Pass", "Quick Resume", "Backward compatibility"],
        inStock: true,
        rating: 4.8,
        reviews: 278,
        isNew: false,
        fastDelivery: true,
        popular: true
    }
];

// Статистика проекта
let projectStats = {
    totalOrders: 42,
    totalProducts: products.length,
    totalRevenue: 1250000
};

// Категории
const categories = [
    { id: "all", name: "Все товары", icon: "📦" },
    { id: "smartphones", name: "Смартфоны", icon: "📱" },
    { id: "laptops", name: "Ноутбуки", icon: "💻" },
    { id: "audio", name: "Аудио", icon: "🎧" },
    { id: "tablets", name: "Планшеты", icon: "📟" },
    { id: "wearables", name: "Гаджеты", icon: "⌚" },
    { id: "gaming", name: "Игровые", icon: "🎮" }
];